apiVersion: apps/v1
kind: Deployment
metadata:
  name: avira-frontend
  labels:
    app: avira-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: avira-frontend
  template:
    metadata:
      labels:
        app: avira-frontend
    spec:
      containers:
        - name: avira-frontend
          image: ogadityahota/avira-frontend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
            requests:
              memory: "128Mi" 
              cpu: "250m"
          securityContext:
            runAsUser: 0
            allowPrivilegeEscalation: false
          # Mount the required volumes
          volumeMounts:
            - name: nginx-temp
              mountPath: /var/cache/nginx
            - name: nginx-run
              mountPath: /var/run
            - name: nginx-logs
              mountPath: /var/log/nginx
          # Add environment variables from ConfigMap
          envFrom:
            - configMapRef:
                name: avira-frontend-config
      volumes:
        - name: nginx-temp
          emptyDir: {}
        - name: nginx-run
          emptyDir: {}
        - name: nginx-logs
          emptyDir: {}