apiVersion: apps/v1
kind: Deployment
metadata:
  name: avira-backend
  labels:
    app: avira-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: avira-backend
  template:
    metadata:
      labels:
        app: avira-backend
    spec:
      containers:
        - name: avira-backend
          image: ogadityahota/avira-backend:latest
          ports:
            - containerPort: 3000
          imagePullPolicy: Always
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 20
            periodSeconds: 5
            timeoutSeconds: 2
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 2
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"
          env:
            - name: REDIS_URL
              valueFrom:
                configMapKeyRef:
                  name: avira-backend-config
                  key: REDIS_URL
            - name: EMAIL_HOST
              valueFrom:
                configMapKeyRef:
                  name: avira-backend-config
                  key: EMAIL_HOST
            - name: EMAIL_PORT
              valueFrom:
                configMapKeyRef:
                  name: avira-backend-config
                  key: EMAIL_PORT
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: avira-backend-secrets
                  key: DATABASE_URL
            - name: CLERK_PUBLISHABLE_KEY
              valueFrom:
                secretKeyRef:
                  name: avira-backend-secrets
                  key: CLERK_PUBLISHABLE_KEY
            - name: CLERK_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: avira-backend-secrets
                  key: CLERK_SECRET_KEY
            - name: EMAIL_USER
              valueFrom:
                secretKeyRef:
                  name: avira-backend-secrets
                  key: EMAIL_USER
            - name: EMAIL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: avira-backend-secrets
                  key: EMAIL_PASSWORD